name: myapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path: ^1.9.1
  image_picker: ^1.1.2
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  emoji_picker_flutter: ^4.3.0
  intl: ^0.20.2
  connectivity_plus: ^6.1.4
  file_picker: ^10.1.9

  #download and save file
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1

  external_path: ^2.2.0

  #Download Image
  saver_gallery: ^4.0.1

#  Save data when offline
  realm: ^20.1.1

#  Web socket
#  web_socket_channel: ^3.0.3
#  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
#  Web socket
#  json_serializable: ^6.9.5

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/emoji_icon.png
    - assets/images/attach.png
    - assets/images/image.png
    - assets/images/no_avatar.jpg
